#!/usr/bin/env node
/**
 * PreToolUse hook: stop Claude editing generated, vendored or secret files by hand.
 *
 * DENY  = regenerated by a build step or fetched from elsewhere, so a manual edit is lost or wrong.
 * ASK   = legitimate to edit, but the team owns it or it has release impact.
 * Matching is case-insensitive: Windows and macOS filesystems are, so `Vendor/x.php` is `vendor/x.php`.
 * Only guards the Edit/Write tools; Bash is covered by permission rules in settings.json.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { projectRootFor } from "./project-root.mjs";

const DENY = [
	[/^(vendor|node_modules|chunks|build)\//i, "is installed or built output. Change the source or the dependency manifest, then re-run the build."],
	[/\.min\.(js|css)$/i, "is minified output. Edit the un-minified source, then run `pnpm exec grunt js` (or `css`)."],
	[/(-rtl\.css|\.css\.map)$/i, "is generated by `pnpm exec grunt css`. Edit the .scss source."],
	[/^languages\//i, "is generated by `pnpm run makepot` and translate.wordpress.org; CONTRIBUTING.md says not to edit it."],
	[/^\.themegrill-qa\/\.env\.local$/i, "holds local QA credentials and must never be edited or committed."],
	[/^\.themegrill-qa\/(docs\/|docs-index\.json$)/i, "is ingested docs cache; regenerate it with the claudegrill ingest script."],
];

const ASK = [
	[/^CHANGELOG\.txt$/i, "is maintained by the release team (CONTRIBUTING.md)."],
	[/^(pnpm-lock\.yaml|composer\.lock)$/i, "is a lockfile; change it through pnpm/composer, not by hand."],
	[/^includes\/libraries\//i, "is third-party code excluded from linting; edit only to apply a deliberate upstream update."],
	[/^\.github\/workflows\//i, "is shared CI (build, QA, release, sync to Pro); a change affects every PR."],
];

/**
 * Classify a project-relative path.
 *
 * @param {string} rel Forward-slash path relative to the project root.
 * @param {(p: string) => boolean} exists Filesystem probe, injectable for tests.
 * @returns {{decision: "deny"|"ask", reason: string} | null}
 */
export function classify(rel, exists = fs.existsSync) {
	for (const [re, why] of DENY) {
		if (re.test(rel)) return { decision: "deny", reason: `${rel} ${why}` };
	}
	const scssSource = rel.replace(/\.css$/i, ".scss");
	if (/^assets\/css\/.+\.css$/i.test(rel) && exists(scssSource)) {
		return { decision: "deny", reason: `${rel} is compiled from ${scssSource}. Edit the .scss, then run \`pnpm exec grunt css\`.` };
	}
	for (const [re, why] of ASK) {
		if (re.test(rel)) return { decision: "ask", reason: `${rel} ${why}` };
	}
	return null;
}

/**
 * Resolve a tool file_path to a forward-slash path relative to the project, or null if outside it.
 *
 * @param {string} filePath Path from the tool input (absolute or relative).
 * @param {string} root Project root.
 * @returns {string|null}
 */
export function toRelative(filePath, root) {
	const rel = path.relative(root, path.resolve(root, filePath));
	if (!rel || rel.startsWith("..") || path.isAbsolute(rel)) return null;
	return rel.split(path.sep).join("/");
}

function main() {
	const input = JSON.parse(fs.readFileSync(0, "utf8"));
	const filePath = input.tool_input?.file_path;
	if (!filePath) return;
	const root = projectRootFor(filePath, input);
	const rel = toRelative(filePath, root);
	if (!rel) return;
	const hit = classify(rel, (p) => fs.existsSync(path.join(root, p)));
	if (!hit) return;
	process.stdout.write(
		JSON.stringify({
			hookSpecificOutput: {
				hookEventName: "PreToolUse",
				permissionDecision: hit.decision,
				permissionDecisionReason: hit.reason,
			},
		}),
	);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
	try {
		main();
	} catch (err) {
		console.error(`guard-files hook failed: ${err.message}`);
		process.exit(1);
	}
}
