#!/usr/bin/env node
/**
 * PreToolUse hook: stop Claude editing generated, vendored or secret files by hand.
 *
 * DENY  = regenerated by a build step or fetched from elsewhere, so a manual edit is lost or wrong.
 * ASK   = legitimate to edit, but the team owns it or it has release impact.
 * Matching is case-insensitive: Windows and macOS filesystems are, so `Vendor/x.php` is `vendor/x.php`.
 * Symlinks and junctions are resolved, so a link to a protected path does not bypass the guard.
 * Only guards the Edit/Write tools; Bash is covered by permission rules in settings.json.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { projectRootFor } from "./project-root.mjs";

const DENY = [
	[/^(vendor|node_modules|chunks|build)\//i, "is installed or built output. Change the source or the dependency manifest, then re-run the build."],
	[/\.min\.(js|css)$/i, "is minified output. Edit the un-minified source, then run `pnpm exec grunt js` (or `css`)."],
	[/(-rtl\.css|\.css\.map)$/i, "is generated by `pnpm exec grunt css`. Edit the .scss source."],
	[/^languages\//i, "is generated by `pnpm run makepot` and translate.wordpress.org; CONTRIBUTING.md says not to edit it."],
	[/^\.themegrill-qa\/\.env\.local$/i, "holds local QA credentials and must never be edited or committed."],
	[/(^|\/)\.env(\.[^/]*)?$/i, "holds environment secrets (matches settings.json's Read deny rules) and must never be edited or committed."],
	[/^\.themegrill-qa\/(docs\/|docs-index\.json$)/i, "is ingested docs cache; regenerate it with the claudegrill ingest script."],
];

const ASK = [
	[/^CHANGELOG\.txt$/i, "is maintained by the release team (CONTRIBUTING.md)."],
	[/^(pnpm-lock\.yaml|composer\.lock)$/i, "is a lockfile; change it through pnpm/composer, not by hand."],
	[/^includes\/libraries\//i, "is third-party code excluded from linting; edit only to apply a deliberate upstream update."],
	[/^\.github\/workflows\//i, "is shared CI (build, QA, release, sync to Pro); a change affects every PR."],
];

/**
 * Classify a project-relative path.
 *
 * @param {string} rel Forward-slash path relative to the project root.
 * @param {(p: string) => boolean} exists Filesystem probe, injectable for tests.
 * @returns {{decision: "deny"|"ask", reason: string} | null}
 */
export function classify(rel, exists = fs.existsSync) {
	for (const [re, why] of DENY) {
		if (re.test(rel)) return { decision: "deny", reason: `${rel} ${why}` };
	}
	const scssSource = rel.replace(/\.css$/i, ".scss");
	if (/^assets\/css\/.+\.css$/i.test(rel) && exists(scssSource)) {
		return { decision: "deny", reason: `${rel} is compiled from ${scssSource}. Edit the .scss, then run \`pnpm exec grunt css\`.` };
	}
	for (const [re, why] of ASK) {
		if (re.test(rel)) return { decision: "ask", reason: `${rel} ${why}` };
	}
	return null;
}

/**
 * Resolve a tool file_path to a forward-slash path relative to the project, or null if outside it.
 *
 * @param {string} filePath Path from the tool input (absolute or relative).
 * @param {string} root Project root.
 * @returns {string|null}
 */
export function toRelative(filePath, root) {
	const rel = path.relative(root, path.resolve(root, filePath));
	if (!rel || rel.startsWith("..") || path.isAbsolute(rel)) return null;
	return rel.split(path.sep).join("/");
}

const MAX_LINK_HOPS = 8;
const STRICTNESS = { deny: 2, ask: 1 };

/**
 * Resolve symlinks and junctions in a path whose tail may not exist yet.
 *
 * Follows the nearest existing ancestor, and a dangling link one hop at a time, so a path that is
 * written through a link resolves to the file that would really be changed.
 *
 * @param {string} p Absolute or relative path.
 * @param {number} [hops] Link hops already followed (guards against loops).
 * @returns {string} Absolute path with links resolved where possible.
 */
export function realPathLoose(p, hops = 0) {
	let current = path.resolve(p);
	const rest = [];
	for (;;) {
		try {
			return path.join(fs.realpathSync.native(current), ...rest);
		} catch {
			// Missing tail or dangling link: fall through and resolve it below.
		}
		const stat = fs.lstatSync(current, { throwIfNoEntry: false });
		if (stat?.isSymbolicLink() && hops < MAX_LINK_HOPS) {
			const target = path.resolve(path.dirname(current), fs.readlinkSync(current));
			return path.join(realPathLoose(target, hops + 1), ...rest);
		}
		const parent = path.dirname(current);
		if (parent === current) return path.resolve(p);
		rest.unshift(path.basename(current));
		current = parent;
	}
}

/**
 * Decide whether an edit needs blocking or confirmation, judging both the path as written and
 * the real path after resolving symlinks, and returning the stricter verdict.
 *
 * @param {string} filePath Path from the tool input.
 * @param {string} root Project root.
 * @param {(p: string) => boolean} [exists] Filesystem probe, injectable for tests.
 * @returns {{decision: "deny"|"ask", reason: string} | null}
 */
export function decide(filePath, root, exists = fs.existsSync) {
	const realRoot = realPathLoose(root);
	const candidates = [
		[toRelative(filePath, root), root],
		[toRelative(realPathLoose(path.resolve(root, filePath)), realRoot), realRoot],
	];
	let strictest = null;
	for (const [rel, base] of candidates) {
		if (!rel) continue;
		const hit = classify(rel, (p) => exists(path.join(base, p)));
		if (hit && (!strictest || STRICTNESS[hit.decision] > STRICTNESS[strictest.decision])) strictest = hit;
	}
	return strictest;
}

function main() {
	const input = JSON.parse(fs.readFileSync(0, "utf8"));
	const filePath = input.tool_input?.file_path;
	if (!filePath) return;
	const root = projectRootFor(filePath, input);
	const hit = decide(filePath, root);
	if (!hit) return;
	process.stdout.write(
		JSON.stringify({
			hookSpecificOutput: {
				hookEventName: "PreToolUse",
				permissionDecision: hit.decision,
				permissionDecisionReason: hit.reason,
			},
		}),
	);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
	try {
		main();
	} catch (err) {
		console.error(`guard-files hook failed: ${err.message}`);
		process.exit(1);
	}
}
