themegrill/user-registration-pro@release/1516-make-form-payment-fields-legacy-membership-field-becomes-the-only-payment-path-for-new-sites:
    - source: assets
      exclude: |
        js/divi-vb-modules.js
    - includes
    - modules
    - src
    - templates
    - .editorconfig
    - .gitattributes
    - .gitignore
    - license.txt
    - phpcs.xml
    - uninstall.php
    - wpml-config.xml
    - tests/e2e
    - playwright.config.ts
