themegrill/user-registration-pro@release/v6.2.8:
    - source: assets
      exclude: |
        js/divi-vb-modules.js
    - includes
    - modules
    - src
    - templates
    - .editorconfig
    - .gitattributes
    - .gitignore
    - license.txt
    - phpcs.xml
    - uninstall.php
    - wpml-config.xml
    - tests/e2e
    - playwright.config.ts
